package com.will.play.mine.entity

data class MineTalentRecordDataListsEntity(
    val commission: String,
    val commission_rate: String,
    val daren_id: String,
    val daren_name: String,
    val daren_nickname: String,
    val daren_type_img_text: String,
    val date_create: String,
    val disable: Int,
    val disable_name: String,
    val disable_text: String,
    val from_id: String,
    val from_name: String,
    val goods_image: String,
    val goods_image_text: String,
    val goods_name: String,
    val goods_price: String,
    val group_id: Int,
    val group_name: String,
    val id: Int,
    val status: Int,
    val status_name: String,
    val tb_id: String,
    val time_apply: Int,
    val time_create: Int,
    val time_create_text: String,
    val time_edit: Int,
    val total_commission: String,
    val total_commission_text: String,
    val total_order: String,
    val total_order_text: String,
    val total_view: String,
    val total_view_text: String,
    val url: String
)